[package]
name = "gilboost-core"
version = "0.2.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
pyo3 = { version = "0.21", features = ["extension-module"] }
futures = "0.3"
async-stream = "0.3"
